### ISSUE TITLE
Spring Cloud Greenwich.SR2 版本不能兼容

### ISSUE THREAD

**Issue by jiulingchen** [SpringCloud/venus-cloud-feign#7]
core 下面的VenusFeignAutoConfig.feignSpringMvcContract()的parameterProcessors傳遞的為null，是不是這個版本的不能兼容 Greenwich.SR2

**Comment by visionwang** [comment]
> core 下面的VenusFeignAutoConfig.feignSpringMvcContract()的parameterProcessors傳遞的為null，是不是這個版本的不能兼容 Greenwich.SR2

请问下，这个版本兼容问题解决了吗

**Comment by SoftwareKing** [comment]
对，不兼容，有兴趣可以贡献。@jiulingchen @visionwang

**Comment by MsencSir** [comment]
![image](https://user-images.githubusercontent.com/46589466/94270995-8ec7c480-ff73-11ea-876c-19e76460eaef.png)
这个原因是版本不兼容吗 我用的是Hoxton.RELEASE

**Comment by MsencSir** [comment]
![image](https://user-images.githubusercontent.com/46589466/94271130-c5054400-ff73-11ea-9be1-499a6bc13ad2.png)
这个原因是版本不兼容吗 我用的是Hoxton.RELEASE

**Comment by MsencSir** [comment]
我的cloud版本用的是Hoxton.RELEASE  启动报错 是版本原因吗
Caused by: java.lang.NullPointerException: null
	at cn.springcloud.feign.VenusSpringMvcContract.<init>(VenusSpringMvcContract.java:53) ~[venus-cloud-feign-core-1.0.0.jar:na]
	at cn.springcloud.feign.VenusFeignAutoConfig.feignSpringMvcContract(VenusFeignAutoConfig.java:56) ~[venus-cloud-feign-core-1.0.0.jar:na]
	at cn.springcloud.feign.VenusFeignAutoConfig$$EnhancerBySpringCGLIB$$48d2e2d7.CGLIB$feignSpringMvcContract$2(<generated>) ~[venus-cloud-feign-core-1.0.0.jar:na]
	at cn.springcloud.feign.VenusFeignAutoConfig$$EnhancerBySpringCGLIB$$48d2e2d7$$FastClassBySpringCGLIB$$eeb1cd40.invoke(<generated>) ~[venus-cloud-feign-core-1.0.0.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
